package ru.bardinpetr.itmo.lab5.network.app.server.modules.auth.errors;

public class UserExistsException extends Exception {
}
